### ISSUE TITLE
Cannot use ARG on Dockerfile using alpine:latest

### ISSUE THREAD

**Issue by jgarces-pd** [alpinelinux/docker-alpine#157]
### I'm trying to do this:

docker-compose.yml
```yaml
   node_01:
      build:
        context: ${NODE_CONTEXT}
        args:
          IMAGE: ${NODE_IMAGE}
          NODE_PASS: rundeckpassword
      links:
        - rundeck_01
        - rundeck_02
      ports:
        - ${NODE_PORT}:22
```

Dockerfile
```dockerfile
ARG IMAGE
ARG NODE_PASS

FROM ${IMAGE}
RUN getent group rundeck || addgroup rundeck
RUN getent passwd rundeckuser || adduser rundeckuser -h /home/rundeck -s /bin/sh -G rundeck -D
RUN passwd -d rundeckuser
RUN echo -e "${NODE_PASS}\n${NODE_PASS}" | passwd rundeckuser > /output
RUN echo "password_env: $NODE_PASS" >> /output
RUN echo "password_dock: ${NODE_PASS}" >> /output
```

The variable **${NODE_PASS}** is not printed out inside the alpine container.

I use this same on another containers like nginx, ubuntu, etc, and those works.

Is there a missing implementation here??

<img width="326" alt="Screen Shot 2021-03-12 at 11 40 33 AM" src="https://user-images.githubusercontent.com/74255967/110954909-cd85e700-8327-11eb-8aa6-b6635f3a76c6.png">
