### ISSUE TITLE
crond does not "read"/"see" crontab on linux host 

### ISSUE THREAD

**Issue by pandaatrail** [alpinelinux/docker-alpine#78]
Hi all,

Using Docker and a `docker:dind` image (but I already tried with custom `alpine:edge` build too), I encounter a strange bug, if this is really a bug and not a misunderstanding from me:

- on Mac OS, my docker-compose stack is working as expected
- on AWS EC2, the exact same stack is **NOT** working as expected

My `docker-compose.yaml`:

```
  cron:
    command: crond -f -d 0 -l 0
    environment:
      ...
    image: docker:dind
    volumes:
      - "./crontab:/etc/crontabs/root"
      - "./periodic:/etc/periodic"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
```

The crontab file is:

```
*/1       *      *       *       *       run-parts /etc/periodic/custom
```

While my custom folder is the parent of the next scripts:

```
touch /tmp/$(date +%Y%m%d-%H:%M:%S)
```

Again, this is working on a Mac with `Docker Desktop 2.2.0.5`, but **NOT** working on an *AWS EC2* instance, with docker `Docker version 18.09.9-ce, build 039a7df`:

- the crond command starts and a `ps aux` gives me the same output on both hosts:

```
PID   USER     TIME  COMMAND
    1 root      0:00 crond -f -d 0 -l 0
```

**I must add that if I trigger `run-parts /etc/periodic/custom` manually, files under `/tmp` are created as expected.**
So the problem might be at startup. It's like if crond was not able to read crontab. Yet, when I log the cron service, I can see:

```
cron_1              | crond: wakeup dt=60
cron_1              | crond: file root:
cron_1              | crond:  line run-parts /etc/periodic/custom
cron_1              | crond:  line run-parts /etc/periodic/custom
```

in the "faulty" AWS EC2 instance.

Is this a bug or am I simply dumb ?

Thanks to anyone that could help me.

**UPDATE**

If I change:

`*       *      *       *       *       run-parts /etc/periodic/custom`
by
`*       *      *       *       *       /bin/sh -c /etc/periodic/custom/test`

It works...

There is definitely something between `crond` and `run-parts`.
